#!/usr/bin/env python
# This file is part of Viper - https://github.com/viper-framework/viper
# See the file 'LICENSE' for copying permission.

import argparse

from viper.core.ui import console
from viper.core.logger import init_logger
from viper.core.project import __project__

parser = argparse.ArgumentParser()
parser.add_argument(
    '-p',
    '--project',
    help='Specify a new or existing project name',
    action='store',
    required=False)

parser.add_argument(
    '--log',
    default="./viper.log",
    help='Logfile (default: ./viper.log)')

parser.add_argument(
    '-d',
    '--debug',
    action='store_true',
    help='Enable debugging')

args = parser.parse_args()

if args.project:
    __project__.open(args.project)

log = init_logger(log_file_path=args.log, debug=args.debug)
log.info('Starting viper-cli')

c = console.Console()
c.start()

